### ISSUE TITLE
CI fails because "build.ps1 -restore" command stops if dotnet SDK version (global.json) is not available

### ISSUE THREAD

**Issue by Bertk** [Bertk/arcade-light#129]
**Describe the bug**
CI build fails after 90 minutes (pipeline timeout). "build.ps1 -restore" command stops if dotnet SDK version (global.json) is not available.

**CI:**
 - vmimage: windows-latest, ubuntu-latest
 - Version of DotNetDev.ArcadeLight.Sdk 1.5.53

**Additional context**
Azure vmimages will not always provide latest dotnet SDK versions
- [windows-latest](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)
- [ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md)

**Comment by Bertk** [comment]
Workaround: Always execute **UseDotNet@2** before `Build.ps1 -restore` is executed

```yml
        - task: UseDotNet@2
          displayName: 'Use dotnet SDK (global)'
          inputs:
            packageType: 'sdk'
            useGlobalJson: true
```
